### PR TITLE
Mobile without preceding zero

### PR DESCRIPTION
**Pull request by Dobbler**
Hi,

I came across the need for this option and thought it might be useful to add. It's working very well for me. 

Regards,

Rob. (github noob, apologies if this is all wrong!)

### CODE REVIEW

**Comment by kenguest** [comment]
Hi - thanks for that. It looks good and I'll take a closer look at it later on.

**Comment by kenguest** [comment]
hi @Dobbler - I ran some tests with your code, by adding four extra lines to the tests/validate_IE_phoneNumber.phpt file and then doing "$ pear run-tests" in that tests directory. 

It let parsed '86 123456' and '86 1245678' as valid - they aren't. One is a number too short and the other a number too many.

Could you take a look at your changes please and tighten up the checks for these edge cases?

**Comment by Dobbler** [comment]
Hi Ken, 

Ah, I'm stripping out everything but digits before I send the number so I haven't run into the space issue.. I'll take a look when I have some more time..  Cheers

**Comment by CloCkWeRX** [comment]
For now, going to close this one off - conflicts, plus the test issues mentioned above. Feel free to reopen a renewed version :)

**Pull request closed without merging**
